require("lazy").setup({
	"NMAC427/guess-indent.nvim",
	require("plugins/greeter"),
	require("plugins/breadcrumbs"),
	require("plugins/comment"),
	require("plugins/completion"),
	require("plugins/explorer"),
	require("plugins/find"),
	require("plugins/format"),
	require("plugins/git"),
	require("plugins/highlight"),
	require("plugins/keys"),
	require("plugins/lsp"),
	require("plugins/mark"),
	require("plugins/move"),
	require("plugins/notify"),
	require("plugins/statusline"),
	require("plugins/surround"),
	require("plugins/syntax"),
	require("plugins/terminal"),
	require("plugins/theme"),
	require("plugins/transparent"),
	require("plugins/select"),
}, {
	ui = {
		-- If you are using a Nerd Font: set icons to an empty table which will use the
		-- default lazy.nvim defined Nerd Font icons, otherwise define a unicode icons table
		icons = vim.g.have_nerd_font and {} or {
			cmd = "⌘",
			config = "🛠",
			event = "📅",
			ft = "📂",
			init = "⚙",
			keys = "🗝",
			plugin = "🔌",
			runtime = "💻",
			require = "🌙",
			source = "📄",
			start = "🚀",
			task = "📌",
			lazy = "💤 ",
		},
	},
})
